 
import React, { PropsWithChildren } from 'react'
import NavBar from '../ui/NavBar'
import Head from 'next/head'
import Footer from '../ui/Footer'
import {
  AiFillAccountBook,
  AiOutlineMenu,
  AiOutlineClose,
  AiOutlineWhatsApp
  
} from "react-icons/ai";

interface Props{
    title?: string
}
// const origin = (typeof window === 'undefined'?'':window.location.origin)
const Layout = ({children,title}:PropsWithChildren<Props>) => {
  return (
    < > 
    <Head>
        <title>{title || "Pokemon App"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <meta property="og:title" content={`Informacion sobre ${title}`} />
        <meta
          property="og:description"
          content={`esta es la pagina sobre${title}`}
        />
        <meta
          property="og:image"
          // content={`${origin}/img/banner.png`}
        />
      </Head>
      <NavBar />


      <main className=''
        
      >
        <div className='fixed bottom-2 rounded-full p-3 left-2 bg-green-500'>
            <a className='text-lg' target='_blank' href="https://wa.me/51953306637"> <i className="fa fa-phone"></i>
        <AiOutlineWhatsApp className='text-4xl text-white md:animate-pulse' href=' '/> </a>
        </div>
        {children}
      </main>
      <Footer/>
      
    
    
    </ >
  )
}

export default Layout